### ISSUE TITLE
xkos:generalizes/xkos:specializes and xkos:hasPart/xkos:isPartOf

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/xkos#32]
This is one of the comments made by Antoine Isaac (see issue #26):

xkos:generalizes/xkos:specializes and xkos:hasPart/xkos:isPartOf. wouldn't the properties of the thesaurus standard ISO 25964 (broaderGeneric) skos-thes:broaderGeneric/skos-thes:narrowerGeneric and skos-thes:broaderPartitive/skos-thes:narrowerPartitive appropriate for this? This would be a great way to link standards of different communities, which I believe are really compatible together.

**Comment by metad8a** [comment]
This proposal makes sense to me. Standards should be linked where appropriate. We should either change the names of the properties or at least use some notation to indicate the equivalence between the XKOS ones and SKOS. When XKOS was first developed, we were unaware of ISO 25964. SKOS used to be based on ISO 2788, which did not differentiate generic and partitive relations.

**Comment by FranckCo** [comment]
The ISO 25964 properties considered are described in http://purl.org/iso25964/skos-thes.

There is agreement to consider that the XKOS and SKOS-Thes properties are equivalent, but the difficulty is that we made xkos:hasPart/isPartOf properties sub-properties of dcterms:hasPart/isPartOf (see issue #25), whereas skos-thes:narrowerPartitive/broaderPartitive are not sub-properties of dcterms:hasPart/isPartOf.

Consequently, it is difficult to declare equivalency between xkos:hasPart/isPartOf and skos-thes:narrowerPartitive/broaderPartitive.

In contrast, there is no difficulty to declare equivalency between xkos:generalizes/specializes and skos-thes:narrowerGeneric/broaderGeneric.

**Comment by tfrancart** [comment]
+1 to link or reuse isothes. From my experience it can be dangerous to directly extend the dcterms properties since they don't have an OWL semantic (see http://bloody-byte.net/rdf/dc_owl2dl/index.html). I would recommend using instead links with weaker semantics (rdfs:seeAlso typically). See also the discussion on "soft ontology reuse" : https://lists.w3.org/Archives/Public/public-lod/2017Jan/0045.html

**Comment by aisaac** [comment]
I agree with a 'soft re-use' option for skos-thes:broaderPartitive/skos-thes:narrowerPartitive, considering the argument above on the (lack of) relationship with dcterms properties. 
But for xkos:generalizes/specializes and skos-thes:narrowerGeneric/broaderGeneric if there's no proof of a semantic difference declaring an equivalence (or directly re-use them) would still seem appropriate.

**Comment by metad8a** [comment]
I can’t find any mention of a Generic relation in SKOS. I found hierarchical relations defined in terms of transitivity, symmetry, and reflexivity. Both the Generic and Partitive relations are hierarchical in this sense. Yet, the semantic interpretation of Generic and Partitive relations are different. One (Generic) is about specialization (such as with the meaning of terms in a classification scheme), and the other (Partitive) is about part/whole (such as the parts and assemblies in a car). Now, maybe this distinction is what people mean when they use the term pragmatics rather than semantics. I don’t know. I do know we need the distinction.


Dan Gillman
US Bureau of Labor Statistics
Office of Survey Methods Research
2 Massachusetts Ave, NE
OSMR, Rm 5930
Washington, DC 21208 USA
Tel. +1.202.691.7523
FAX +1.202.691.7426
Email Gillman.Daniel@BLS.Gov<mailto:Gillman.Daniel@BLS.Gov>
________________________
“Whatever it is, I’m against it!
No matter what it is or who
commenced it, I’m against it!”
   ~ Groucho Marx

**Comment by aisaac** [comment]
The distinction between generic and partitive is indeed a feature of the ISO-thes extension at http://purl.org/iso25964/skos-thes, not SKOS.

**Comment by metad8a** [comment]
Thank you for the clarification. However, the definitions at http://purl.org/iso25964/skos-thes just aren’t clearly what is needed for XKOS. The definition for Generic refers to “classes”, not “concepts”, and the definition for Partitive talks about how the use of the relation should lead to transitive closure. Now, I’ve read ISO 25964-1, and if those definitions are inherited, then I am OK. We can say with assurance that the xkos usages of Generic and Partitive are the same as skos-thes.


Dan Gillman
US Bureau of Labor Statistics
Office of Survey Methods Research
2 Massachusetts Ave, NE
OSMR, Rm 5930
Washington, DC 21208 USA
Tel. +1.202.691.7523
FAX +1.202.691.7426
Email Gillman.Daniel@BLS.Gov<mailto:Gillman.Daniel@BLS.Gov>
________________________
“Whatever it is, I’m against it!
No matter what it is or who
commenced it, I’m against it!”
   ~ Groucho Marx

**Comment by aisaac** [comment]
Many occurrences of 'class' at http://purl.org/iso25964/skos-thes are purely technical (as in "the class of SKOS concepts"), not about KOS semantics. There's a couple of "class-instance" or "class-class" occurrences however, that are relevant for the semantics of KOS to be represented by the SKOS ISO extension, such as for http://purl.org/iso25964/skos-thes#broaderInstantial or, indeed, http://pub.tenforce.com/schemas/iso25964/skos-thes/#broaderGeneric . As far as I can remember when creating these properties we didn't mean to deviate from the ISO 25964-1 meaning. Actually I can't remember any discussion at that time on what was intended by "class" (or "generic"). We (at least I) just assumed it meant whatever ISO 25964-1 was meaning for these constructs.

**Comment by metad8a** [comment]
OK. If all of this is true – the definitions are what they say in ISO 25964-1 – then we can say xkos:Generalizes is the same as skos-thes:broaderGeneric, etc.


Dan Gillman
US Bureau of Labor Statistics
Office of Survey Methods Research
2 Massachusetts Ave, NE
OSMR, Rm 5930
Washington, DC 21208 USA
Tel. +1.202.691.7523
FAX +1.202.691.7426
Email Gillman.Daniel@BLS.Gov<mailto:Gillman.Daniel@BLS.Gov>
____________________________________
In theory, theory and practice are the same.
In practice, they are not.
   ~ Anonymous

**Comment by aisaac** [comment]
Hello, someone on the SKOS list asked about the status of this issue. It would be great to know at least whether there is opposition to the principle of the mapping (even if it's not added in an XKOS release yet)
