### ISSUE TITLE
Explanatory notes

### ISSUE THREAD

**Issue by makxdekkers** [linked-statistics/xkos#59]
I am wondering whether the elaborate structure of explanatory notes in section 8.2 may be confusing. The question is whether implementers and users really understand the differences and provide the content in the 'right' fields. It may be that statistical classification experts already have the relevant information structured in this way, but will it be useful for others? In addition, there seems to be semantic overlap between additionalContentNote and inclusionNote – as both may refer to ‘things’ that are included – and between additionalContentNote and caseLaw – as both may refer to decisions. This may create confusion.

**Comment by tfrancart** [comment]
- the semantic overlap between additionalContentNote and inclusionNote is actually intended since, as depicted in the diagram and explained in the text, additionalContentNote is a subPropertyOf inclusionNote.
- the statistical classification community does have use-cases to use these types of notes, as shown by issue #45
