### ISSUE TITLE
Reuse of oa:Annotation for xkos:ExplanatoryNote and xkos:plainText

### ISSUE THREAD

**Issue by makxdekkers** [linked-statistics/xkos#66]
Instead of declaring the XKOS-specific class xkos:ExplanatoryNote, could an alternative be to reuse the more general oa:Annotation? If the range of the notes properties was declared as oa:Annotation, the Open Annotation machinery for allowing various types of content types (see: https://www.w3.org/TR/annotation-model/#bodies-and-targets) would be immediately available without the need to declare the XKOS-specific class and xkos:plainText property.

**Comment by tfrancart** [comment]
- XKOS does not declare a formal range for the note properties.
- We don't think oa:Annotation is an appropriate choice as the range of a note property, because an Annotation "MUST [have] 1 or more target relationships associated with [it]", since an Annotation captures the fact that "someone says something about an existing resource"
- However, if you have a case for using oa:Annotation as values for note properties, you are free to do so in XKOS;
- Annotating classifications could be useful in the phase where classifications are created, when collaborative suggestions are being made.
